name: ✨ 功能请求 (中文)
description: 建议新功能或改进
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        **感谢您分享关于Prism Code Plus的想法!**
        在提交功能请求之前，请搜索[现有请求](../../issues?q=is%3Aissue+label%3Aenhancement)以避免重复。

  - type: textarea
    id: problem
    attributes:
      label: 要解决的问题
      description: 描述此功能将解决的问题或不便。清晰的使用案例会很有帮助。
      placeholder: |
        例如: 在[情况]下使用Prism时，[问题]发生。
        这导致[不便/限制]。
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 详细描述所需的功能或行为。
      placeholder: |
        例如: 添加[功能]将提供[好处]。
        工作方式:
        1. 当用户执行[操作]时
        2. Prism执行[动作]
        3. 显示[结果]。
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 (可选)
      description: 如果您考虑过其他解决方案或变通方法，请描述它们。
      placeholder: 目前这样变通...
    validations:
      required: false

  - type: dropdown
    id: feature-category
    attributes:
      label: 功能类别
      description: 请选择此功能所属的类别。
      options:
        - AI/模型相关
        - 代码编辑与生成
        - UI/UX
        - 性能优化
        - 集成与扩展性 (MCP等)
        - 文件与项目管理
        - 调试与错误处理
        - 设置与自定义
        - 其他
      default: 8
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 优先级 (主观)
      description: 您认为这个功能有多重要?
      options:
        - 非常高 - 当前使用有重大限制
        - 高 - 经常需要且对效率有重大影响
        - 中等 - 有更好但不是必需的
        - 低 - 锦上添花
      default: 2
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 附加信息
      description: 请添加任何有用的信息，如截图、示例代码或参考资料。
      placeholder: |
        - 其他工具中类似功能的链接
        - 模型或截图
        - 代码示例
    validations:
      required: false
